version: "2"
services: 
  stable-diffusion-rocm-docker:
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      # VERY COMMON NEED ENVIRONMENT VARIABLE
      - HSA_OVERRIDE_GFX_VERSION=10.3.4
    image: 1naforever/stable-diffusion-rocm:latest
    ipc: host
    network_mode: "host"
    security_opt:
      - seccomp:unconfined
    volumes:
      - modules:/sd/modules
      - models:/sd/models
      - plugins:/sd/plugins
volumes:
  modules:
  models:
  plugins: 
